version: '3'
services:

  simple-payment-api:
    container_name: simple-payment-api
    image: zabini/simple-payment-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: build/Dockerfile
    command: ["php", "/opt/www/bin/hyperf.php", "start"]
    volumes:
      - ./:/opt/www:cached
    ports:
      - 9501:9501
    networks:
      - simple-payment-net
    depends_on:
      - simple-payment-db

  simple-payment-db:
    container_name: simple-payment-db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - simple-payment-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - simple-payment-net

volumes:
  simple-payment-data:

networks:
  simple-payment-net:
